---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-ws-ex2-fend

spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: k8-ws-ex2-fend
          image: vdeepak0792/k8-ws-pageview2:1.01
