---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: k8-ws-ex2-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: k8-ws-ex2-redis
          image: redis
